---
AWSTemplateFormatVersion: 2010-09-09
Description: >
    This template deploys Amazon SageMaker Notebook Instance By Author:Felix
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required SageMaker Parameters
        Parameters:
          - NotebookInstanceType
          - GithubRepo
          - EBSSize
Parameters:
  NotebookInstanceType:
    AllowedValues:
      - ml.m5.xlarge
      - ml.m5.2xlarge
    ConstraintDescription: Must select a valid notebook instance type.
    Default: ml.m5.xlarge
    Description: Select Instance type for the SageMaker Notebook
    Type: String
  GithubRepo:
    Type: String
    Default: "https://github.com/brilliantwf/SDonEKS-Deploy.git"
    Description: Github Repository
  EBSSize: 
    Type: Number
    Default: 200
    Description: EBS Size Default Size is 200GB
Resources:
  ExecutionRole: 
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "sagemaker.amazonaws.com"
                - "cloudformation.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
# NOTEBOOK -----------------------------------------------------
  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: !Ref 'NotebookInstanceType'
      RoleArn: !GetAtt ExecutionRole.Arn
      VolumeSizeInGB: !Ref 'EBSSize'
      LifecycleConfigName: !GetAtt BasicNotebookInstanceLifecycleConfig.NotebookInstanceLifecycleConfigName
  BasicNotebookInstanceLifecycleConfig:
    Type: "AWS::SageMaker::NotebookInstanceLifecycleConfig"
    Properties:
      OnStart:
        - Content:
            Fn::Base64: !Sub |
              #!/bin/bash
              set -e
              cd /home/ec2-user/SageMaker
              git clone --recurse-submodules -j8 ${GithubRepo}
              echo "c.NotebookApp.terminado_settings={'shell_command': ['/bin/bash']}" | tee -a /home/ec2-user/.jupyter/jupyter_notebook_config.py >/dev/null
              sudo chown -R ec2-user:ec2-user /home/ec2-user/SageMaker
              sudo systemctl restart jupyter-server --no-block
# END NOTEBOOK -------------------------------------------------

Outputs:
  Repo:
    Value: !Sub ${GithubRepo}
  NotebookInstanceLab:
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/openNotebook/${NotebookInstance.NotebookInstanceName}?view=lab"
    Description: Notebook Instance Lab