modelBucketArn: 'arn:aws:s3:::sd-model-store'
modelsRuntime:
- name: "sdruntime1"
  namespace: "sdruntime1"
  modelFilename: "v1-5-pruned-emaonly.safetensors"
  chartRepository: "544592066775.dkr.ecr.us-east-1.amazonaws.com/sd-on-eks/charts/sd-on-eks"
  chartVersion: "0.2.0"
  extraValues:
    karpenter:
      nodeTemplate:
        amiFamily: Bottlerocket
        dataVolume:
          volumeSize: 80Gi
          volumeType: gp3
          deleteOnTermination: true
          iops: 4000
          throughput: 1000
          snapshotID: snap-03fa79a10917af68d
    sdWebuiInferenceApi:
      inferenceApi:
        image:
          repository: 544592066775.dkr.ecr.us-east-1.amazonaws.com/sd-on-eks/inference-api
          tag: latest
      queueAgent:
        image:
          repository: 544592066775.dkr.ecr.us-east-1.amazonaws.com/sd-on-eks/queue-agent
          tag: latest
      persistence:
        enabled: true
        existingClaim: "efs-model-storage-pvc"
- name: "sdruntime2"
  namespace: "sdruntime2"
  modelFilename: "revAnimated_v122.safetensors"
  chartRepository: "544592066775.dkr.ecr.us-east-1.amazonaws.com/sd-on-eks/charts/sd-on-eks"
  chartVersion: "0.2.0"
  extraValues:
    karpenter:
      nodeTemplate:
        amiFamily: Bottlerocket
        dataVolume:
          volumeSize: 80Gi
          volumeType: gp3
          deleteOnTermination: true
          iops: 4000
          throughput: 1000
          snapshotID: snap-03fa79a10917af68d
    sdWebuiInferenceApi:
      inferenceApi:
        image:
          repository: 544592066775.dkr.ecr.us-east-1.amazonaws.com/sd-on-eks/inference-api
          tag: latest
      queueAgent:
        image:
          repository: 544592066775.dkr.ecr.us-east-1.amazonaws.com/sd-on-eks/queue-agent
          tag: latest
      persistence:
        enabled: true
        existingClaim: "efs-model-storage-pvc"
dynamicModelRuntime:
  enabled: true
  namespace: "default"